issuehunt: RebeccaStevens/template-typescript-node-package
ko_fi: rebeccastevens
tidelift: npm/template-typescript-node-package
custom: https://github.com/RebeccaStevens/template-typescript-node-package/blob/main/DONATIONS.md
