issuehunt: RebeccaStevens/template-typescript-node-package
ko_fi: rebeccastevens
tidelift: npm/__package_name__
custom: https://github.com/RebeccaStevens/template-typescript-node-package/blob/main/DONATIONS.md
